## **Numpy Recap on May 11**

In [1]:
import numpy as np

In [2]:
l = list(range(1,10))
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
l = range(10000000)
%timeit [i**2 for i in l]

731 ms ± 99.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
arr = np.array(l)
%timeit arr**2

19.9 ms ± 611 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [6]:
a = list(range(0,16))
arr1 = np.array(a)
arr1.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [7]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### **2D Array**

In [8]:
arr2 = arr1.reshape(4,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
arr2.shape, arr2.ndim

((4, 4), 2)

### **3D Array**

In [10]:
arr = np.arange(0,27)
arr3 = arr.reshape(3,3,3)
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [11]:
arr3.shape, arr3.ndim

((3, 3, 3), 3)

In [12]:
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [13]:
arr4 = np.arange(1,10,0.5)
arr4

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [14]:
arr4.shape, arr4.ndim

((18,), 1)

### **Array Type Conversion**

In [15]:
arr5 = np.array([1,"Chaitu",3.5,True])
arr5

array(['1', 'Chaitu', '3.5', 'True'], dtype='<U32')

In [16]:
arr6 = np.array([1,4.5,True])
arr6

array([1. , 4.5, 1. ])

In [17]:
arr7 = np.array([1,True])
arr7

array([1, 1])

### **DType & Astype**

In [18]:
a = np.array([1,2,3,4])
a.dtype

dtype('int64')

In [19]:
b = np.array([1,2,3,4], dtype = "float64")
b

array([1., 2., 3., 4.])

In [20]:
b.astype("str")

array(['1.0', '2.0', '3.0', '4.0'], dtype='<U32')

### **Indexing**

In [21]:
a = np.arange(0,19)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [22]:
a[0],a[9], a[[2,4]],a[[-1,1,-2,2]]

(0, 9, array([2, 4]), array([18,  1, 17,  2]))

### **Slicing**

In [23]:
a[2:5]

array([2, 3, 4])

In [24]:
a[4:9]

array([4, 5, 6, 7, 8])

In [25]:
a[-5:-1]

array([14, 15, 16, 17])

In [26]:
a < 6

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [27]:
a[a<6]

array([0, 1, 2, 3, 4, 5])

In [28]:
a = np.random.randint(1,100,10)
b = np.random.randint(1,100,10)

In [29]:
# Checking equality
a == b

array([False, False, False, False, False, False, False, False, False,
       False])

In [30]:
# Getting even and odd index
a[::2], a[1::2]

(array([89, 83, 93,  3, 22]), array([13, 59, 98, 56, 61]))

In [31]:
a[[0,2,4]]

array([89, 83, 93])

### **Reading file**

In [32]:
score = np.loadtxt("survey.txt")
score

array([ 7., 10.,  5., ...,  5.,  9., 10.])

In [33]:
# % of promoters
promoters = score[score > 8]
print("% of promoters",len(promoters)/len(score) * 100)
# % of dectractors
dectractors = score[score <= 6]
print("% of dectractors",len(dectractors)/len(score) * 100)

% of promoters 52.185089974293064
% of dectractors 28.449014567266495


In [34]:
NPS = (len(promoters)/len(score) * 100) - (len(dectractors)/len(score) * 100)
NPS

23.73607540702657

### **Reshape**

In [35]:
arr = np.arange(1, 19)
arr.shape

(18,)

In [36]:
arr1 = arr.reshape(3,6)
arr1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [37]:
arr2 = arr.reshape(3, -1)
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [38]:
arr3 = arr.reshape(-1,2)
arr3

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18]])

In [39]:
arr4 = arr.reshape(1,3,6)
arr4

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18]]])

### **Transpose**

In [40]:
a = np.arange(1,17)
a = a.reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [41]:
a.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [42]:
np.transpose(a)

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

### **Indexing in 2D Array**

In [43]:
a 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [44]:
a[2] # Entire row

array([ 9, 10, 11, 12])

In [45]:
a[:,2] # Entire column

array([ 3,  7, 11, 15])

In [46]:
a [2,3] # specific element

12

In [47]:
a[2][3] # Get 3rd row and then 4 element

12

In [48]:
a[[1,2]] # get 2nd and 3rd rows

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
a[[1,2],[2,3]] # get 2nd and 3rd rows and 3rd and 4th columns

array([ 7, 12])

In [50]:
a[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [51]:
a[1:3][1:3]

array([[ 9, 10, 11, 12]])

#### Why difference?

First one takes row and columns

Second one takes rows and creates a temp array and on that again takes rows

### **Masking**

In [52]:
r = np.random.randint(1,100, 15)
mask = r > 15

In [53]:
mask

array([ True,  True,  True, False,  True,  True,  True,  True, False,
        True, False,  True,  True,  True,  True])

In [54]:
r[mask]

array([87, 21, 43, 25, 96, 91, 89, 49, 56, 83, 21, 98])

In [55]:
r2 = np.random.randint(1,50,16).reshape(4,4)
r2

array([[14, 22,  8, 33],
       [45, 47, 24, 13],
       [36, 31, 19, 32],
       [48, 43,  2, 38]])

In [56]:
mask = r2<7
mask

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

In [57]:
r2[mask]

array([2])

In [58]:
r2[mask] = 9999 # assigning at once
r2

array([[  14,   22,    8,   33],
       [  45,   47,   24,   13],
       [  36,   31,   19,   32],
       [  48,   43, 9999,   38]])

### **Aggregate functions**

In [59]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [60]:
print("Sum", np.sum(a))
print("Average: ", np.mean(a))
print("Min: ", np.min(a))
print("Max: ", np.max(a))

Sum 120
Average:  7.5
Min:  0
Max:  15


In [61]:
b = np.random.randint(1,200, (4,4))
b

array([[127, 104,  29, 140],
       [ 85, 199, 193, 186],
       [108,  62,  60,  42],
       [ 40,  24,  84,  48]])

In [62]:
print("Sum: ", np.sum(b))
print("Mean: ", np.mean(b))
print("Min: ",np.min(b))
print("Max: ", np.max(b))

Sum:  1531
Mean:  95.6875
Min:  24
Max:  199


In [63]:
# Row wise
print("Sum: ", np.sum(b, axis = 0))
print("Mean: ", np.mean(b, axis = 0))
print("Min: ",np.min(b, axis = 0))
print("Max: ", np.max(b, axis = 0))

Sum:  [360 389 366 416]
Mean:  [ 90.    97.25  91.5  104.  ]
Min:  [40 24 29 42]
Max:  [127 199 193 186]


In [64]:
# Column wise
print("Sum: ", np.sum(b, axis = 1))
print("Mean: ", np.mean(b, axis = 1))
print("Min: ",np.min(b, axis = 1))
print("Max: ", np.max(b, axis = 1))

Sum:  [400 663 272 196]
Mean:  [100.   165.75  68.    49.  ]
Min:  [29 85 42 24]
Max:  [140 199 108  84]


### **Logical Functions**

In [65]:
mask1 = [True, False, True, True]
np.any(mask1), np.all(mask1)

(True, False)

In [66]:
prices = np.array([50,45,25,20,35,70])
budget = 40
# any prices less than 40 ?
np.any(prices < budget)

True

In [67]:
# All prices less than 40
np.all(prices < budget)

False

In [68]:
arr = np.random.randint(-20, 20, 10)
arr

array([  4,  -9,  -3, -18,   9,  -3,  -9,  11,   4,  16])

In [70]:
np.where(arr < 0, "invalid",arr)

array(['4', 'invalid', 'invalid', 'invalid', '9', 'invalid', 'invalid',
       '11', '4', '16'], dtype='<U21')

In [72]:
np.where(arr > 5, arr *0.9,arr)

array([  4. ,  -9. ,  -3. , -18. ,   8.1,  -3. ,  -9. ,   9.9,   4. ,
        14.4])