## **Numpy Recap on May 11**

In [1]:
import numpy as np

In [2]:
l = list(range(1,10))
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
l = range(10000000)
%timeit [i**2 for i in l]

693 ms ± 12.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
arr = np.array(l)
%timeit arr**2

22.2 ms ± 2.02 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [6]:
a = list(range(0,16))
arr1 = np.array(a)
arr1.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [7]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### **2D Array**

In [8]:
arr2 = arr1.reshape(4,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
arr2.shape, arr2.ndim

((4, 4), 2)

### **3D Array**

In [10]:
arr = np.arange(0,27)
arr3 = arr.reshape(3,3,3)
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [11]:
arr3.shape, arr3.ndim

((3, 3, 3), 3)

In [12]:
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [13]:
arr4 = np.arange(1,10,0.5)
arr4

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [14]:
arr4.shape, arr4.ndim

((18,), 1)

### **Array Type Conversion**

In [15]:
arr5 = np.array([1,"Chaitu",3.5,True])
arr5

array(['1', 'Chaitu', '3.5', 'True'], dtype='<U32')

In [16]:
arr6 = np.array([1,4.5,True])
arr6

array([1. , 4.5, 1. ])

In [17]:
arr7 = np.array([1,True])
arr7

array([1, 1])

### **DType & Astype**

In [18]:
a = np.array([1,2,3,4])
a.dtype

dtype('int64')

In [19]:
b = np.array([1,2,3,4], dtype = "float64")
b

array([1., 2., 3., 4.])

In [20]:
b.astype("str")

array(['1.0', '2.0', '3.0', '4.0'], dtype='<U32')

### **Indexing**

In [21]:
a = np.arange(0,19)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [22]:
a[0],a[9], a[[2,4]],a[[-1,1,-2,2]]

(0, 9, array([2, 4]), array([18,  1, 17,  2]))

### **Slicing**

In [23]:
a[2:5]

array([2, 3, 4])

In [24]:
a[4:9]

array([4, 5, 6, 7, 8])

In [25]:
a[-5:-1]

array([14, 15, 16, 17])

In [26]:
a < 6

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [27]:
a[a<6]

array([0, 1, 2, 3, 4, 5])

In [28]:
a = np.random.randint(1,100,10)
b = np.random.randint(1,100,10)

In [29]:
# Checking equality
a == b

array([False, False, False, False, False, False, False, False, False,
       False])

In [30]:
# Getting even and odd index
a[::2], a[1::2]

(array([22, 29, 90, 27, 26]), array([61, 91, 72, 65, 12]))

In [31]:
a[[0,2,4]]

array([22, 29, 90])

### **Reading file**

In [32]:
score = np.loadtxt("survey.txt")
score

array([ 7., 10.,  5., ...,  5.,  9., 10.])

In [33]:
# % of promoters
promoters = score[score > 8]
print("% of promoters",len(promoters)/len(score) * 100)
# % of dectractors
dectractors = score[score <= 6]
print("% of dectractors",len(dectractors)/len(score) * 100)

% of promoters 52.185089974293064
% of dectractors 28.449014567266495


In [34]:
NPS = (len(promoters)/len(score) * 100) - (len(dectractors)/len(score) * 100)
NPS

23.73607540702657

### **Reshape**

In [35]:
arr = np.arange(1, 19)
arr.shape

(18,)

In [36]:
arr1 = arr.reshape(3,6)
arr1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [37]:
arr2 = arr.reshape(3, -1)
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [38]:
arr3 = arr.reshape(-1,2)
arr3

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18]])

In [39]:
arr4 = arr.reshape(1,3,6)
arr4

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18]]])

### **Transpose**

In [40]:
a = np.arange(1,17)
a = a.reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [41]:
a.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [42]:
np.transpose(a)

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

### **Indexing in 2D Array**

In [43]:
a 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [44]:
a[2] # Entire row

array([ 9, 10, 11, 12])

In [45]:
a[:,2] # Entire column

array([ 3,  7, 11, 15])

In [46]:
a [2,3] # specific element

12

In [47]:
a[2][3] # Get 3rd row and then 4 element

12

In [48]:
a[[1,2]] # get 2nd and 3rd rows

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
a[[1,2],[2,3]] # get 2nd and 3rd rows and 3rd and 4th columns

array([ 7, 12])

In [50]:
a[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [51]:
a[1:3][1:3]

array([[ 9, 10, 11, 12]])

#### Why difference?

First one takes row and columns

Second one takes rows and creates a temp array and on that again takes rows

### **Masking**

In [52]:
r = np.random.randint(1,100, 15)
mask = r > 15

In [53]:
mask

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True])

In [54]:
r[mask]

array([52, 61, 59, 74, 53, 34, 74, 28, 20, 37, 39, 76, 71, 43])

In [55]:
r2 = np.random.randint(1,50,16).reshape(4,4)
r2

array([[26, 33,  3, 27],
       [20, 47, 42, 33],
       [ 4, 36, 47,  1],
       [34,  6, 14, 38]])

In [56]:
mask = r2<7
mask

array([[False, False,  True, False],
       [False, False, False, False],
       [ True, False, False,  True],
       [False,  True, False, False]])

In [57]:
r2[mask]

array([3, 4, 1, 6])

In [58]:
r2[mask] = 9999 # assigning at once
r2

array([[  26,   33, 9999,   27],
       [  20,   47,   42,   33],
       [9999,   36,   47, 9999],
       [  34, 9999,   14,   38]])

### **Aggregate functions**

In [59]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [60]:
print("Sum", np.sum(a))
print("Average: ", np.mean(a))
print("Min: ", np.min(a))
print("Max: ", np.max(a))

Sum 120
Average:  7.5
Min:  0
Max:  15


In [61]:
b = np.random.randint(1,200, (4,4))
b

array([[182,  16,  12, 177],
       [ 71,  10,  89,  54],
       [118, 106, 149,   6],
       [184,  12,  49,  88]])

In [62]:
print("Sum: ", np.sum(b))
print("Mean: ", np.mean(b))
print("Min: ",np.min(b))
print("Max: ", np.max(b))

Sum:  1323
Mean:  82.6875
Min:  6
Max:  184


In [63]:
# Row wise
print("Sum: ", np.sum(b, axis = 0))
print("Mean: ", np.mean(b, axis = 0))
print("Min: ",np.min(b, axis = 0))
print("Max: ", np.max(b, axis = 0))

Sum:  [555 144 299 325]
Mean:  [138.75  36.    74.75  81.25]
Min:  [71 10 12  6]
Max:  [184 106 149 177]


In [64]:
# Column wise
print("Sum: ", np.sum(b, axis = 1))
print("Mean: ", np.mean(b, axis = 1))
print("Min: ",np.min(b, axis = 1))
print("Max: ", np.max(b, axis = 1))

Sum:  [387 224 379 333]
Mean:  [96.75 56.   94.75 83.25]
Min:  [12 10  6 12]
Max:  [182  89 149 184]


### **Logical Functions**

In [65]:
mask1 = [True, False, True, True]
np.any(mask1), np.all(mask1)

(True, False)

In [66]:
prices = np.array([50,45,25,20,35,70])
budget = 40
# any prices less than 40 ?
np.any(prices < budget)

True

In [67]:
# All prices less than 40
np.all(prices < budget)

False

In [68]:
arr = np.random.randint(-20, 20, 10)
arr

array([ 16,   9,   5,  18,  -2,  19,   6,  -2, -10, -10])

In [69]:
np.where(arr < 0, "invalid",arr)

array(['16', '9', '5', '18', 'invalid', '19', '6', 'invalid', 'invalid',
       'invalid'], dtype='<U21')

In [70]:
np.where(arr > 5, arr *0.9,arr)

array([ 14.4,   8.1,   5. ,  16.2,  -2. ,  17.1,   5.4,  -2. , -10. ,
       -10. ])

### **Fitbit**

In [71]:
fit = np.loadtxt("fit.txt", dtype = 'str')
fit

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [72]:
type(fit)

numpy.ndarray

In [73]:
fit.shape, fit.size, fit.ndim

((96, 6), 576, 2)

In [74]:
fit[0]

array(['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
      dtype='<U10')

In [75]:
fit.T

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-

In [76]:
fit.T.shape

(6, 96)

In [77]:
a,b,c,d = np.array([[1],[2],[3],[4]])
a,b,c,d

(array([1]), array([2]), array([3]), array([4]))

In [78]:
date, step_count,mood, calories_burned, hours_sleep, activity_status = fit.T

In [79]:
date.dtype, step_count.dtype,mood.dtype, calories_burned.dtype, hours_sleep.dtype, activity_status.dtype

(dtype('<U10'),
 dtype('<U10'),
 dtype('<U10'),
 dtype('<U10'),
 dtype('<U10'),
 dtype('<U10'))

In [80]:
step_count = step_count.astype("int64")
hours_sleep = hours_sleep.astype("int64")
calories_burned = calories_burned.astype("int64")

In [81]:
date.dtype, step_count.dtype,mood.dtype, calories_burned.dtype, hours_sleep.dtype, activity_status.dtype

(dtype('<U10'),
 dtype('int64'),
 dtype('<U10'),
 dtype('int64'),
 dtype('int64'),
 dtype('<U10'))

In [82]:
np.unique(mood)

array(['Happy', 'Neutral', 'Sad'], dtype='<U10')

In [83]:
fit[mood == "Happy"]

array([['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['29-10-2017', '330', 'Happy', '10', '6', 'Inactive'],
       ['31-10-2017', '4550', 'Happy', '150', '8', 'Active'],
       ['01-11-2017', '4435', 'Happy', '141', '5', 'Inactive'],
       ['02-11-2017', '4779', 'Happy', '156', '4', 'Inactive'],
       ['03-11-2017', '1831', 'Happy', '57', '5', 'Inactive'],
       ['04-11-2017', '2255', 'Happy', '72', '4', 'Inactive'],
       ['05-11-2017', '539', 'Happy', '17', '5', 'Active'],
       ['06-11-2017', '5464', 'Happy', '181', '4', 'Inactive'],
       ['08-11-2017', '4068', 'Happy', '131', '2', 'Inactive'],
       ['09-11-2017', '4683', 'Happy', '154', '9', 'Inactive'],
       ['10-11-2017', '4033', 'Happy', '137', '5', 'Inactive'],
       ['11-11-2017', '6314', 'Happy', '193', '6', 'Active'],
       ['12-11-2017', '614', 'Happy', '19', '4', 'Active'],
       ['13-11-2017', '3149', 'Happy', '101', '5', 'Active'],
       ['14-11-2017', '4005', 'Happy', '139', '8', 'Active']

In [84]:
step_count[mood == "Happy"]

array([4732,  330, 4550, 4435, 4779, 1831, 2255,  539, 5464, 4068, 4683,
       4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  269, 4275, 5999,
       4421, 6930, 5195,  546,  493,  995, 3608,  774, 1421, 4064, 2725,
       5934, 1867, 7422, 5537, 5376,  153, 2203])

In [85]:
# Mean of Mood happy
np.mean(step_count[mood == "Happy"])

3392.725

In [86]:
np.mean(step_count[mood == "Sad"])

2103.0689655172414

### **Sorting Array**

In [87]:
a = np.random.randint(1,100,10)
a

array([71, 68, 97,  9, 90, 89, 33, 91, 14, 64])

In [88]:
# Temp
np.sort(a),a

(array([ 9, 14, 33, 64, 68, 71, 89, 90, 91, 97]),
 array([71, 68, 97,  9, 90, 89, 33, 91, 14, 64]))

In [89]:
a.sort()

In [90]:
a

array([ 9, 14, 33, 64, 68, 71, 89, 90, 91, 97])

#### **2D Array**

**Why This Makes Sense**

    Axis Definition: In NumPy, axis=0 always refers to the first dimension (rows in 2D), and axis=1 refers to the second dimension (columns in 2D). Sorting along an axis sorts the elements in that dimension while grouping by the other dimension.
    Consistency: This convention is consistent with other NumPy operations (e.g., sum, mean):
        axis=0: Operates along rows, producing results for each column.
        axis=1: Operates along columns, producing results for each row.
    Higher Dimensions: The logic extends to higher-dimensional arrays. For a 3D array, axis=0 sorts along the first dimension (depth), axis=1 along the second (rows), and axis=2 along the third (columns).

**For a 2D array:**

    axis=0 (column-wise): Sorts each column independently, moving values along rows.
    axis=1 (row-wise): Sorts each row independently, moving values along columns.

In [91]:
a = np.random.randint(1,100,16)
b = a.reshape(4,4)
b

array([[76, 97, 46, 93],
       [67, 10, 68, 40],
       [34, 89, 74, 74],
       [16, 49, 44, 76]])

In [92]:
np.sort(b)

array([[46, 76, 93, 97],
       [10, 40, 67, 68],
       [34, 74, 74, 89],
       [16, 44, 49, 76]])

In [93]:
np.sort(b, axis = 0)

array([[16, 10, 44, 40],
       [34, 49, 46, 74],
       [67, 89, 68, 76],
       [76, 97, 74, 93]])

In [94]:
np.sort(b, axis = 1)

array([[46, 76, 93, 97],
       [10, 40, 67, 68],
       [34, 74, 74, 89],
       [16, 44, 49, 76]])

#### **3D Arrays**

In [95]:
a = np.random.randint(1, 1000,(3,5,5))
a

array([[[ 24, 962, 983, 355, 933],
        [ 17, 874, 674,  45, 371],
        [977,  13, 666, 262, 534],
        [714,  81, 858, 164, 925],
        [494, 315,  73, 614, 356]],

       [[586, 411, 784, 503, 835],
        [901,  37, 319,  94, 516],
        [501, 156, 706, 772, 633],
        [769, 820, 144, 871, 340],
        [536, 254,  39, 486, 554]],

       [[638, 647, 663, 864, 321],
        [150, 691, 752, 312, 796],
        [611, 708, 453,  27, 778],
        [776, 539, 459, 490, 341],
        [ 80, 900, 880, 233, 195]]])

In [96]:
np.sort(a, axis = 0)

array([[[ 24, 411, 663, 355, 321],
        [ 17,  37, 319,  45, 371],
        [501,  13, 453,  27, 534],
        [714,  81, 144, 164, 340],
        [ 80, 254,  39, 233, 195]],

       [[586, 647, 784, 503, 835],
        [150, 691, 674,  94, 516],
        [611, 156, 666, 262, 633],
        [769, 539, 459, 490, 341],
        [494, 315,  73, 486, 356]],

       [[638, 962, 983, 864, 933],
        [901, 874, 752, 312, 796],
        [977, 708, 706, 772, 778],
        [776, 820, 858, 871, 925],
        [536, 900, 880, 614, 554]]])

In [97]:
np.sort(a, axis = 1)

array([[[ 17,  13,  73,  45, 356],
        [ 24,  81, 666, 164, 371],
        [494, 315, 674, 262, 534],
        [714, 874, 858, 355, 925],
        [977, 962, 983, 614, 933]],

       [[501,  37,  39,  94, 340],
        [536, 156, 144, 486, 516],
        [586, 254, 319, 503, 554],
        [769, 411, 706, 772, 633],
        [901, 820, 784, 871, 835]],

       [[ 80, 539, 453,  27, 195],
        [150, 647, 459, 233, 321],
        [611, 691, 663, 312, 341],
        [638, 708, 752, 490, 778],
        [776, 900, 880, 864, 796]]])

In [98]:
np.sort(a, axis = 2)

array([[[ 24, 355, 933, 962, 983],
        [ 17,  45, 371, 674, 874],
        [ 13, 262, 534, 666, 977],
        [ 81, 164, 714, 858, 925],
        [ 73, 315, 356, 494, 614]],

       [[411, 503, 586, 784, 835],
        [ 37,  94, 319, 516, 901],
        [156, 501, 633, 706, 772],
        [144, 340, 769, 820, 871],
        [ 39, 254, 486, 536, 554]],

       [[321, 638, 647, 663, 864],
        [150, 312, 691, 752, 796],
        [ 27, 453, 611, 708, 778],
        [341, 459, 490, 539, 776],
        [ 80, 195, 233, 880, 900]]])

### **Matrix Multiplication**

In [99]:
a = np.random.randint(1,50, 10)
b = np.random.randint(1,50, 10)
a, b

(array([11, 40, 28, 45,  3, 32, 44,  5,  1, 21]),
 array([34, 23,  4, 10, 39, 12, 18,  5, 12, 45]))

In [100]:
a*5,b *6

(array([ 55, 200, 140, 225,  15, 160, 220,  25,   5, 105]),
 array([204, 138,  24,  60, 234,  72, 108,  30,  72, 270]))

In [101]:
a*b

array([374, 920, 112, 450, 117, 384, 792,  25,  12, 945])

In [102]:
c = np.arange(1,12)
try:
    a*c
except ValueError:
    print("Cannot broadcast")

Cannot broadcast


In [103]:
a = np.random.randint(1, 20, (2,3))
b = np.random.randint(1,200,(3,1))
a @b

array([[2102],
       [2309]])

In [104]:
np.matmul(a, b)

array([[2102],
       [2309]])

In [105]:
np.dot(a,b)

array([[2102],
       [2309]])

#### **Differnce**
differnce between matmul, @ and dot

In [106]:
np.dot(a,5)

array([[10, 60, 75],
       [45, 55, 85]])

In [107]:
try:
    np.matmul(a,5)
except ValueError:
    print("matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)")

matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)


In [108]:
try:
    a @ 5
except ValueError:
    print("matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)")

matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)


### **Vectorization**

In [109]:
a = np.arange(10)
a + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [110]:
a * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [111]:
def even_odd(num):
    if num % 2 == 0:
        return "even"
    return "odd"

In [112]:
try:
    even_odd(a)
except ValueError:
    print("ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()")

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


In [113]:
vec_even_odd = np.vectorize(even_odd)
vec_even_odd(a)

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd'], dtype='<U4')

### **Broadcasting**

**Shape Compatibility**:

    Arrays must have compatible shapes for broadcasting. Two shapes are compatible if:
        They are equal, or
        One of them is 1 in a given dimension, allowing that dimension to be "stretched" to match the other array's size.

**Steps for Broadcasting**:

    Align Dimensions: If arrays have different numbers of dimensions, prepend dimensions of size 1 to the shape of the array with fewer dimensions until both have the same number of dimensions.
    Compare Shapes: Starting from the rightmost dimension (trailing dimensions), compare the sizes:
        Dimensions are compatible if they are equal or one of them is 1.
        If a dimension size is 1, it is stretched to match the other array’s size in that dimension.
    Incompatible Shapes: If dimensions are neither equal nor 1, broadcasting fails, raising a ValueError.

In [114]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [115]:
a + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [116]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [117]:
a + b

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18]])

In [118]:
c = np.arange(8).reshape(2,4)
c

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [119]:
try:
    a+c
except ValueError:
    print("ValueError: operands could not be broadcast together with shapes (4,4) (2,4) ")

ValueError: operands could not be broadcast together with shapes (4,4) (2,4) 


In [120]:
d = np.random.randint(1,20,(4,1))
d

array([[ 9],
       [13],
       [17],
       [10]])

In [121]:
a + d

array([[ 9, 10, 11, 12],
       [17, 18, 19, 20],
       [25, 26, 27, 28],
       [22, 23, 24, 25]])

### **Shallow copy and Deep copy**

#### **Shallow copy**

In [122]:
a = np.arange(4)
b = a.reshape(2,2)
a,b

(array([0, 1, 2, 3]),
 array([[0, 1],
        [2, 3]]))

In [123]:
b[1,1] = 300
b

array([[  0,   1],
       [  2, 300]])

In [124]:
a

array([  0,   1,   2, 300])

Both a and b are updated

In [125]:
c = a[::2]
c

array([0, 2])

In [126]:
c[1] = 200
c

array([  0, 200])

In [127]:
a

array([  0,   1, 200, 300])

Both a and c are updated

In [128]:
d = a.view()
d

array([  0,   1, 200, 300])

In [129]:
d[1] = 100
d

array([  0, 100, 200, 300])

In [130]:
a

array([  0, 100, 200, 300])

Both a and d are updated

#### **Deep Copy**

Deep copy is created when there is change in elements

Arithmetic operations, Masking, copy

In [131]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [132]:
b = a+ 1
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [133]:
b[15] = 160
b

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15, 160])

In [134]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Both a and b are different

In [135]:
c = a * 2
c[15] = 300
c

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28, 300])

In [136]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Both are different

In [137]:
d = a[a %2 == 0]
d

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [138]:
d[7] = 140
d

array([  0,   2,   4,   6,   8,  10,  12, 140])

In [139]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Both a and d are different

In [140]:
e = a.copy()
e[15]= 150
a, e

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]),
 array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14, 150]))

Both a and e are different

#### **Shares Memory**

In [141]:
np.shares_memory(a,b)

False

In [142]:
arr1 = np.arange(4)
arr2 = arr1[::2]
np.shares_memory(arr1,arr2)

True

#### **Object Array**

In [143]:
arr1 = np.array([1,"Chaitanya",9.8])
arr1.dtype

dtype('<U32')

In [144]:
arr2 = arr1.copy()
arr2[1] = "Sagar"
arr1, arr2

(array(['1', 'Chaitanya', '9.8'], dtype='<U32'),
 array(['1', 'Sagar', '9.8'], dtype='<U32'))

In [145]:
from copy import deepcopy
arr3 = deepcopy(arr1)
arr3[1] = "Sagar"
arr1, arr3

(array(['1', 'Chaitanya', '9.8'], dtype='<U32'),
 array(['1', 'Sagar', '9.8'], dtype='<U32'))

In [146]:
np.shares_memory(arr1,arr2), np.shares_memory(arr1,arr3)

(False, False)

### **Splitting**

In [147]:
a = np.arange(16)
b = np.split(a, 4)

In [148]:
b

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([12, 13, 14, 15])]

In [149]:
try:
    b.dtype
except AttributeError:
    print("AttributeError: 'list' object has no attribute 'dtype'")

AttributeError: 'list' object has no attribute 'dtype'


When an array is split, a list with array of equal size is returned

In [150]:
try:
    c = np.split(a, 3)
except ValueError:
    print("array split does not result in an equal division")

array split does not result in an equal division


When we try to split an array with unequal size, throws an Value error 

#### **Horizontal Splitting**

In [151]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [152]:
np.hsplit(a, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [153]:
np.hsplit(a, [2,3])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

#### **Vertical Split**

In [154]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [155]:
np.vsplit(a, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [156]:
np.vsplit(a, [2,3])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

### **Stacking**

In [157]:
a = np.arange(0,4)
b = np.arange(4,8)
c = np.arange(8,12)
d = np.arange(12,16)
a,b,c,d

(array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([12, 13, 14, 15]))

In [158]:
np.vstack([a,b,c,d])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [159]:
a = np.arange(4).reshape(4,1)
b = np.arange(4,8).reshape(4,1)
c = np.arange(8,12).reshape(4,1)
d = np.arange(12,16).reshape(4,1)
np.hstack([a,b,c,d])

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

### **Concatenate**

In [160]:
a = np.arange(4)
b = np.arange(4, 16).reshape(3,4)
a,b

(array([0, 1, 2, 3]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [161]:
try:
    np.concatenate([a,b])
except ValueError:
    print("Throws below error as dim of a is 1")
    print("ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)")

Throws below error as dim of a is 1
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)


In [162]:
a = a.reshape(1,4)
a

array([[0, 1, 2, 3]])

In [163]:
np.concatenate([a,b]) # Wont throw exception and joins at vertical 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [164]:
np.concatenate([a,b],axis = 0) # Same as above

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Axis = 0 joins on vertical level

In [165]:
a = np.arange(4).reshape(4,1)
b = np.arange(4, 16).reshape(4,3)
a, b, 

(array([[0],
        [1],
        [2],
        [3]]),
 array([[ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]]))

In [166]:
np.concatenate([a,b], axis = 1) # Joins horizontally

array([[ 0,  4,  5,  6],
       [ 1,  7,  8,  9],
       [ 2, 10, 11, 12],
       [ 3, 13, 14, 15]])

In [167]:
np.concatenate([a,b], axis = None)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Flattening of array