## **Numpy Recap on May 11**

In [1]:
import numpy as np

In [2]:
l = list(range(1,10))
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
l = range(10000000)
%timeit [i**2 for i in l]

778 ms ± 130 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
arr = np.array(l)
%timeit arr**2

20.5 ms ± 1.31 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [8]:
a = list(range(0,16))
arr1 = np.array(a)
arr1.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### **2D Array**

In [12]:
arr2 = arr1.reshape(4,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
arr2.shape, arr2.ndim

((4, 4), 2)

### **3D Array**