In [1]:
import pandas as pd

# Read Titanic dataset using Pandas
titanic_data = pd.read_csv('titanic_numpy.csv')

# Convert Pandas DataFrame to NumPy array
titanic_array = titanic_data.values

In [2]:
import numpy as np

In [3]:
titanic_data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [4]:
titanic_array

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], dtype=object)

1) Type Conversion in NumPy Arrays:\
Question: Convert the 'Age' column of the Titanic dataset to a NumPy array with float data type.
Solution

In [5]:
titanic_array.shape # Shape of the array

(891, 12)

In [6]:
titanic_array_T = titanic_array.T

In [7]:
age = titanic_array_T[5].astype('float64')

In [8]:
age.dtype

dtype('float64')

2) Indexing & Slicing:\
Question: Print the details of passengers with passenger ID 10 to 20.

In [9]:
titanic_array[9:20]

array([[10, 1, 2, 'Nasser, Mrs. Nicholas (Adele Achem)', 'female', 14.0,
        1, 0, '237736', 30.0708, nan, 'C'],
       [11, 1, 3, 'Sandstrom, Miss. Marguerite Rut', 'female', 4.0, 1, 1,
        'PP 9549', 16.7, 'G6', 'S'],
       [12, 1, 1, 'Bonnell, Miss. Elizabeth', 'female', 58.0, 0, 0,
        '113783', 26.55, 'C103', 'S'],
       [13, 0, 3, 'Saundercock, Mr. William Henry', 'male', 20.0, 0, 0,
        'A/5. 2151', 8.05, nan, 'S'],
       [14, 0, 3, 'Andersson, Mr. Anders Johan', 'male', 39.0, 1, 5,
        '347082', 31.275, nan, 'S'],
       [15, 0, 3, 'Vestrom, Miss. Hulda Amanda Adolfina', 'female', 14.0,
        0, 0, '350406', 7.8542, nan, 'S'],
       [16, 1, 2, 'Hewlett, Mrs. (Mary D Kingcome) ', 'female', 55.0, 0,
        0, '248706', 16.0, nan, 'S'],
       [17, 0, 3, 'Rice, Master. Eugene', 'male', 2.0, 4, 1, '382652',
        29.125, nan, 'Q'],
       [18, 1, 2, 'Williams, Mr. Charles Eugene', 'male', nan, 0, 0,
        '244373', 13.0, nan, 'S'],
       [19, 0, 3,
 

In [10]:
titanic_array[(titanic_array[:,0] >= 10) & (titanic_array[:,0] <=20)] # Using Fancy INdexing

array([[10, 1, 2, 'Nasser, Mrs. Nicholas (Adele Achem)', 'female', 14.0,
        1, 0, '237736', 30.0708, nan, 'C'],
       [11, 1, 3, 'Sandstrom, Miss. Marguerite Rut', 'female', 4.0, 1, 1,
        'PP 9549', 16.7, 'G6', 'S'],
       [12, 1, 1, 'Bonnell, Miss. Elizabeth', 'female', 58.0, 0, 0,
        '113783', 26.55, 'C103', 'S'],
       [13, 0, 3, 'Saundercock, Mr. William Henry', 'male', 20.0, 0, 0,
        'A/5. 2151', 8.05, nan, 'S'],
       [14, 0, 3, 'Andersson, Mr. Anders Johan', 'male', 39.0, 1, 5,
        '347082', 31.275, nan, 'S'],
       [15, 0, 3, 'Vestrom, Miss. Hulda Amanda Adolfina', 'female', 14.0,
        0, 0, '350406', 7.8542, nan, 'S'],
       [16, 1, 2, 'Hewlett, Mrs. (Mary D Kingcome) ', 'female', 55.0, 0,
        0, '248706', 16.0, nan, 'S'],
       [17, 0, 3, 'Rice, Master. Eugene', 'male', 2.0, 4, 1, '382652',
        29.125, nan, 'Q'],
       [18, 1, 2, 'Williams, Mr. Charles Eugene', 'male', nan, 0, 0,
        '244373', 13.0, nan, 'S'],
       [19, 0, 3,
 

3) Fancy Indexing:\
Question: Print the details of passengers with odd passenger IDs.

In [11]:
#titanic_array[:,0] % 2 == 0

In [12]:
titanic_array[titanic_array[:,0] % 2 == 1]

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       [5, 0, 3, ..., 8.05, nan, 'S'],
       ...,
       [887, 0, 2, ..., 13.0, nan, 'S'],
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], dtype=object)

4) 2D Indexing:\
Question: Print the details of passengers in the 3rd row.

5) Masking:\
Question: Print the details of passengers with 'Fare' greater than 100.

In [13]:
#titanic_data

In [14]:
titanic_array[titanic_array[:,9] > 100]

array([[28, 0, 1, 'Fortune, Mr. Charles Alexander', 'male', 19.0, 3, 2,
        '19950', 263.0, 'C23 C25 C27', 'S'],
       [32, 1, 1, 'Spencer, Mrs. William Augustus (Marie Eugenie)',
        'female', nan, 1, 0, 'PC 17569', 146.5208, 'B78', 'C'],
       [89, 1, 1, 'Fortune, Miss. Mabel Helen', 'female', 23.0, 3, 2,
        '19950', 263.0, 'C23 C25 C27', 'S'],
       [119, 0, 1, 'Baxter, Mr. Quigg Edmond', 'male', 24.0, 0, 1,
        'PC 17558', 247.5208, 'B58 B60', 'C'],
       [196, 1, 1, 'Lurette, Miss. Elise', 'female', 58.0, 0, 0,
        'PC 17569', 146.5208, 'B80', 'C'],
       [216, 1, 1, 'Newell, Miss. Madeleine', 'female', 31.0, 1, 0,
        '35273', 113.275, 'D36', 'C'],
       [259, 1, 1, 'Ward, Miss. Anna', 'female', 35.0, 0, 0, 'PC 17755',
        512.3292, nan, 'C'],
       [269, 1, 1, 'Graham, Mrs. William Thompson (Edith Junkins)',
        'female', 58.0, 0, 1, 'PC 17582', 153.4625, 'C125', 'S'],
       [270, 1, 1, 'Bissette, Miss. Amelia', 'female', 35.0, 0, 0,
    

There are total of 53 passengers with Fare greater than 100

6) np.all:\
Question: Check if all 'Fare' values are greater than 0.

In [15]:
np.all(titanic_array[:,9] > 0)

False

7. np.where:\
Question: Find the indices where 'Survived' column is equal to 1.

In [16]:
np.where(titanic_array[:,1] == 1)

(array([  1,   2,   3,   8,   9,  10,  11,  15,  17,  19,  21,  22,  23,
         25,  28,  31,  32,  36,  39,  43,  44,  47,  52,  53,  55,  56,
         58,  61,  65,  66,  68,  74,  78,  79,  81,  82,  84,  85,  88,
         97,  98, 106, 107, 109, 123, 125, 127, 128, 133, 136, 141, 142,
        146, 151, 156, 161, 165, 166, 172, 183, 184, 186, 187, 190, 192,
        193, 194, 195, 198, 204, 207, 208, 209, 211, 215, 216, 218, 220,
        224, 226, 230, 233, 237, 241, 247, 248, 255, 256, 257, 258, 259,
        261, 267, 268, 269, 271, 272, 274, 275, 279, 283, 286, 288, 289,
        290, 291, 298, 299, 300, 301, 303, 305, 306, 307, 309, 310, 311,
        315, 316, 318, 319, 322, 323, 325, 327, 328, 329, 330, 334, 337,
        338, 340, 341, 345, 346, 347, 348, 356, 358, 359, 366, 367, 368,
        369, 370, 375, 376, 380, 381, 383, 387, 389, 390, 391, 393, 394,
        399, 400, 407, 412, 414, 416, 417, 426, 427, 429, 430, 431, 432,
        435, 437, 440, 443, 444, 445, 446, 447, 448

8. np.any:\
Question: Check if any 'Age' value is missing (NaN).

In [17]:
np.any(np.isnan(titanic_array[:,5].astype('float64')))

True

9. Sorting:\
Question: Sort the Titanic array based on 'Fare' column in descending order.

In [18]:
titanic_fare_sort = titanic_array[np.argsort(titanic_array[:,9])[::-1]]
titanic_fare_sort

array([[680, 1, 1, ..., 512.3292, 'B51 B53 B55', 'C'],
       [259, 1, 1, ..., 512.3292, nan, 'C'],
       [738, 1, 1, ..., 512.3292, 'B101', 'C'],
       ...,
       [303, 0, 3, ..., 0.0, nan, 'S'],
       [598, 0, 3, ..., 0.0, nan, 'S'],
       [272, 1, 3, ..., 0.0, nan, 'S']], dtype=object)

10. Matrix Multiplication:\
Question: Find the dot product of 'Age' and 'Fare' columns.

In [19]:
age = titanic_array_T[5].astype('float64')
fare = titanic_array_T[9].astype('float64')
age.shape, fare.shape

((891,), (891,))

In [20]:
np.dot(titanic_array[:,5], titanic_array[:,9])

nan

In [21]:
np.dot(age, fare)

nan

### When NaN is replaced with 0

In [22]:
age = np.where(np.isnan(age), 0, age)
fare = np.where(np.isnan(fare), 0, fare)
np.dot(age, fare)

788357.425814

11. Broadcasting:\
Question: Multiply 'Fare' column by 2 and add 10 to each element.

In [23]:
fare[:5]

array([ 7.25  , 71.2833,  7.925 , 53.1   ,  8.05  ])

In [24]:
new_fare = (fare * 2) + 10
new_fare[:5]

array([ 24.5   , 152.5666,  25.85  , 116.2   ,  26.1   ])

12. Shallow vs Deep Copy:\
Question: Create a shallow copy of the Titanic array and modify a value. Check if the original array is affected.

In [25]:
# Creating a view
titanic_view = titanic_array.view()
titanic_view[:5]

array([[1, 0, 3, 'Braund, Mr. Owen Harris', 'male', 22.0, 1, 0,
        'A/5 21171', 7.25, nan, 'S'],
       [2, 1, 1, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
        'female', 38.0, 1, 0, 'PC 17599', 71.2833, 'C85', 'C'],
       [3, 1, 3, 'Heikkinen, Miss. Laina', 'female', 26.0, 0, 0,
        'STON/O2. 3101282', 7.925, nan, 'S'],
       [4, 1, 1, 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
        'female', 35.0, 1, 0, '113803', 53.1, 'C123', 'S'],
       [5, 0, 3, 'Allen, Mr. William Henry', 'male', 35.0, 0, 0,
        '373450', 8.05, nan, 'S']], dtype=object)

In [26]:
# Updating Survived to 1 for 1st record
titanic_view[0][1] = 1

In [27]:
titanic_view[:5] # Checking view after update

array([[1, 1, 3, 'Braund, Mr. Owen Harris', 'male', 22.0, 1, 0,
        'A/5 21171', 7.25, nan, 'S'],
       [2, 1, 1, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
        'female', 38.0, 1, 0, 'PC 17599', 71.2833, 'C85', 'C'],
       [3, 1, 3, 'Heikkinen, Miss. Laina', 'female', 26.0, 0, 0,
        'STON/O2. 3101282', 7.925, nan, 'S'],
       [4, 1, 1, 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
        'female', 35.0, 1, 0, '113803', 53.1, 'C123', 'S'],
       [5, 0, 3, 'Allen, Mr. William Henry', 'male', 35.0, 0, 0,
        '373450', 8.05, nan, 'S']], dtype=object)

In [28]:
titanic_array[:5] # Checking original array

array([[1, 1, 3, 'Braund, Mr. Owen Harris', 'male', 22.0, 1, 0,
        'A/5 21171', 7.25, nan, 'S'],
       [2, 1, 1, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
        'female', 38.0, 1, 0, 'PC 17599', 71.2833, 'C85', 'C'],
       [3, 1, 3, 'Heikkinen, Miss. Laina', 'female', 26.0, 0, 0,
        'STON/O2. 3101282', 7.925, nan, 'S'],
       [4, 1, 1, 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
        'female', 35.0, 1, 0, '113803', 53.1, 'C123', 'S'],
       [5, 0, 3, 'Allen, Mr. William Henry', 'male', 35.0, 0, 0,
        '373450', 8.05, nan, 'S']], dtype=object)

13. Array Splitting:\
Question: Split the Titanic array into two arrays horizontally.

In [29]:
titanic_array.shape
#np.vsplit(titanic_array, 2)

(891, 12)

In [30]:
np.array_split(titanic_array, 2)

[array([[1, 1, 3, ..., 7.25, nan, 'S'],
        [2, 1, 1, ..., 71.2833, 'C85', 'C'],
        [3, 1, 3, ..., 7.925, nan, 'S'],
        ...,
        [444, 1, 2, ..., 13.0, nan, 'S'],
        [445, 1, 3, ..., 8.1125, nan, 'S'],
        [446, 1, 1, ..., 81.8583, 'A34', 'S']], dtype=object),
 array([[447, 1, 2, ..., 19.5, nan, 'S'],
        [448, 1, 1, ..., 26.55, nan, 'S'],
        [449, 1, 3, ..., 19.2583, nan, 'C'],
        ...,
        [889, 0, 3, ..., 23.45, nan, 'S'],
        [890, 1, 1, ..., 30.0, 'C148', 'C'],
        [891, 0, 3, ..., 7.75, nan, 'Q']], dtype=object)]